// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Action {
    "event": string;
    "payload": any;

    /** Creates a new Action instance. */
    constructor($$source: Partial<Action> = {}) {
        if (!("event" in $$source)) {
            this["event"] = "";
        }
        if (!("payload" in $$source)) {
            this["payload"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Action instance from a string or object.
     */
    static createFrom($$source: any = {}): Action {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Action($$parsedSource as Partial<Action>);
    }
}

export class HandlerResult {
    "items": Result[];

    /** Creates a new HandlerResult instance. */
    constructor($$source: Partial<HandlerResult> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HandlerResult instance from a string or object.
     */
    static createFrom($$source: any = {}): HandlerResult {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new HandlerResult($$parsedSource as Partial<HandlerResult>);
    }
}

export class Result {
    "label": string;
    "subtitle": string;
    "rank": number;
    "icon": string;
    "iconBase64": string;
    "action": Action;

    /** Creates a new Result instance. */
    constructor($$source: Partial<Result> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("subtitle" in $$source)) {
            this["subtitle"] = "";
        }
        if (!("rank" in $$source)) {
            this["rank"] = 0;
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("iconBase64" in $$source)) {
            this["iconBase64"] = "";
        }
        if (!("action" in $$source)) {
            this["action"] = (new Action());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     */
    static createFrom($$source: any = {}): Result {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("action" in $$parsedSource) {
            $$parsedSource["action"] = $$createField5_0($$parsedSource["action"]);
        }
        return new Result($$parsedSource as Partial<Result>);
    }
}

export class SearchParams {
    "query": string;

    /** Creates a new SearchParams instance. */
    constructor($$source: Partial<SearchParams> = {}) {
        if (!("query" in $$source)) {
            this["query"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchParams instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchParams {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchParams($$parsedSource as Partial<SearchParams>);
    }
}

// Private type creation functions
const $$createType0 = Result.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Action.createFrom;
